# Generated by Django 4.0.1 on 2022-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Сделано'),
        ),
    ]
