# Generated by Django 4.0.1 on 2022-01-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_task_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда сделано'),
        ),
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Сделано'),
        ),
    ]
